---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-conf
  namespace: vault
  labels:
    app: consul
data:
  config.json: |
    {
      "ca_file": "/etc/tls/ca.pem",
      "cert_file": "/etc/tls/consul.pem",
      "key_file": "/etc/tls/consul-key.pem",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "ports": {
        "https": 8443
      }
    }